language: node_js
node_js:
- '8'
before_script:
  - 'yarn lint'
notifications:
  email: false
deploy:
  provider: npm
  email: davidstoreypickart@gmail.com
  api_key:
    secure: Hg15C5qgBIaF4bcoM1zU9l5mtv0VekcTz+8FsMfLpLdj5X/l0YwrblRfT6eRNS+3dn5rj8t7lfqS+ikNbpNni98zNU8kF0z5o8XuUzo7PVrnnok2/5Bodnt9pJFCqmxLcfEKT3+yOu1U7kpV0GRW3LsJrCnlQBNWtZH/FYEBvd+6ZV27E3trGVo9Xir24BabxPrIAHBMjdM5N+00O9hfd+y3qW1Rq1p7UpLvhAw8YEhRQcWAuazxZSrzb3GExoEb2SAOm1MWvKe3wrnQ/QsvgABSjdYFViDgdlCb5y+I0mZFFu/TfLKJWGNRfRXgOGygw9Pvy8Rd9ewNQk3b/bIdaEcYa1whGmEJvF6FLZ8R0s3CyiqW6t0UhBti63SuvYnwirttzT1h1Yz0E+G6Un4CBUZQ6GIitF8DdxGdvfP5dIZRmDvUUBIgkLXY5d1QOJGTCM1ufkVAj6QewTA5cbmDsQx1DHAQtHHdDHyAu4EhXZUBbuQiGmYvpq62FZKmBfjNMLO073b4cJ/7H2CZYiQkdBWBfcxkHjGu6CFHMZuCxmqcN3RO6GEu7CCWm8EuTk6KBBsVe89TDU51L1aOzv5BCncSiDz+WEYzduAxlvu/zAW/aOVzmqbHPZdNI3r636Spct2AFyxxqUbEuZK8faOcHftRuMPJyaWHynS1WpYl9tc=
  on:
    branch: master
  skip_cleanup: true
