language: node_js
node_js:
- '8'
before_script:
  - 'yarn lint'
notifications:
  email: false
deploy:
  provider: npm
  email: davidstoreypickart@gmail.com
  api_key:
    secure: cIHqBxkfNldDgaw+IF+o8mWYcleY3bDQgIiSUmMrZVQV3A2eW0cVBeqgvQra+XuJah+uyS7MkeYlWcpLyoS86/+6esW68we8NZeFtriKTVSlySQbVff0wOMHfbK3H9EqNbG1DVZ7H5IlJM7Tek7sULu0qDcB+uXRcNsl9blB+MBt6nkk2/LnNMvjdgKR0QMRN7AhIwOQo5iDY9zc8tUg/1PTuCd13LKXx0QBo0ZCgVWx6PpZED4+7h8k3t9883jq5EGYBvJGXPtxjfxcKvOjoCqZhMuBubUQRkdKT0xEhxVrvfCq9LADpawo0dyb9HY+rlCFN5ZcAw/RcXn5zVgodYe5KtAkk6sV8qm1F2Q5/Ive+MVkk+SBlH05yLMIEE/OGSWlgo60fX6Ta6IYv5BtsXbFyzG2N0/08tZPxt5IuAaNQY1IUx7tS4WnIyqIPRzBzWGAxEHnQf0jwDBnr57I+RCX/2eolkqBNL/LVxcLd85FkyFK9+v85AAOvTsHN0TJ91Ru9nNh4MKPV27Yll0351ZZxw9AFWnB4IywGCXCmbU+FpYOHAJtY+lfbR/7Q0rxXV8eDa3i2qwTfhQczAW0ER4hwped+eo96jERulMSJErSuk3OK59C+9FVmLuv+UE/HDSMGaL/5DIlb0CwyoBGi5IjI/Tdp5cJ8r8SIAmdl8A=
  on:
    branch: master
  skip_cleanup: true
