language: node_js
node_js:
- '8'
before_script:
  - 'yarn lint'
notifications:
  email: false
deploy:
  provider: npm
  email: davidstoreypickart@gmail.com
  api_key:
    secure: FMUQzQQb48YG7sun3O7NpLYajXHwLgHOJ9Q/OBoYDu8Z2APNUVznArp2mpHe23peA/YDHXCyJCVYAyy6RIJ0xP879Zw3xuXiZegYI1wppHIuzZashGZbpCLgnh7kVYKnIHQ2qHJhIxaeOqF44KklYraUJOduw93JNBWlPlyUlc4L4UNF70QUqLyNDpQL6q/PMySzbZ+RDgIHoVmbA1vFIjgJ5zw+yDBKyoF+xjOXsgwfXbkoWNWBVEQJ+5rqysU4bE6Nhy7j8UKuB/KTWSH/imtNmDkapg1RQr5lI1z5+JnANIRFMAGPyW1vhHfvuvIWPyTAGrDn46HjGFmts8V1sJoBMVAZD0rTRh4V3+atCo8ATAkreUndZZrWT8UzESUPgKWsDWvQoksVBQNvyiL7HX5PCAjLe7l5yZBgruKhqLfkBS1yhuzhCIKGNjoBBeURXNXJ4j/Sd/QyIg4JhqWAs8YceqL3S0UAEl288jgPZaZ3HCGHiuaQiqhgPC2RFN63MiHxZLVODlMZdLmU4xlNtSvLXMpHVS8zEl7X5i/clPHdwVkjpKSR6A+ctepH1xck5AM1+TY4zY7TFZ1jOPQ5LTdolcKJu4Dgp700miaYCPusEuWsvs3sUC8MFFre2Ad8eS7RdFSGfnSs46YMXcDshYMLh1xtbMxGIlXcGYMsBek=
  on:
    branch: master
  skip_cleanup: true
